### ISSUE TITLE
[META 27] docs: Add ecs-logging-go-logrus to the Elastic doc build

### ISSUE THREAD

**Issue by bmorelli25** [elastic/ecs-logging-go-logrus#5]
## To do

- [x] Move docs to asciidoc https://github.com/elastic/ecs-logging-go-logrus/pull/9
- [x] Open PR in `elastic/docs` to add to the build https://github.com/elastic/docs/pull/2047
- [x] Open infra ticket to add the `elasticsearch/ci docs` check to this repo (see link in the timeline below)
- [x] Add the `elasticsearch/ci docs` webhook to the repo
- [x] Remove content from readme and link to published docs

Ping me when you're ready for this step and I can help you out!

**Comment by bmorelli25** [comment]
Docs will be live on [elastic.co](https://www.elastic.co/guide/en/ecs-logging/go-logrus/current/index.html) within the hour.
